### PR TITLE
fix: values should be replaced in selectors as well

### PR DESCRIPTION
**Pull request by jquense**

### CODE REVIEW

**Comment by jquense** [comment]
BAH sorry, `prettier` running automatically by accident, i'll fix

**Comment by jquense** [comment]
@evilebottnawi question for you. I'm ultimately trying to get the following to work:

```postcss
@value btn from './btn.module.css';

.foo .btn {
  color: red;
}
```

which (with this change) will _work_ in the isolated case. HOWEVER when used with `postcss-modules-scope` the `.btn` class will get mangled as well since it has no sense that the selector class here is an imported value.

There are a few ways I can think to fix this, one is adding support in `postcss-modules-scope` to not mangle values from `:import()` that match here, but that seems like it might be too much since it will also create potential conflicts with `composes: ` values. 

The other thought was to actual have the value get replaced wrapped in a `:global()` for selectors, not sure if that will work but i'd like your thoughts...

**Comment by evilebottnawi** [comment]
@jquense oh, i just maintenance this repo on bug fixes, don't have time on design, so feel free to experiment

**Comment by evilebottnawi** [comment]
@jquense yep, do this in near future

**Comment by jquense** [comment]
thanks!

**Pull request merged**
